### ISSUE TITLE
mac OS binary problem

### ISSUE THREAD

**Issue by marvpaul** [videokit-ai/videokit#148]
I use VideoKit 0.0.19 and uploaded a binary to appstore connect. Apple connect error when trying to upload Mac binary: ITMS-90288: Invalid Code Signing Entitlements - The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: 'NPA3XMW8F9.' for the key 'com.apple.application-identifier' in 'Fluids.app/Contents/PlugIns/Function.dylib'
ITMS-90286: Invalid Code Signing Entitlements - Your application bundle's signature contains code signing entitlements that are not supported on macOS. Specifically, value 'NPA3XMW8F9.' for key 'com.apple.application-identifier' in 'Fluids.app/Contents/PlugIns/Function.dylib' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier .

How can I fix this?

**Comment by olokobayusuf** [comment]
@marvpaul this looks like it's related to code signing. When building your macOS binary from Unity, are you creating an Xcode project first? If so, can you ensure that you are code signing all bundles? I'll also follow up on Discord.

**Comment by olokobayusuf** [comment]
Fix coming in 0.0.22. Update should go out by EOD today or tomorrow.

**Comment by olokobayusuf** [comment]
[Fixed in 0.0.22](https://github.com/videokit-ai/videokit/releases/tag/0.0.22).

**Comment by marvpaul** [comment]
I think it's not fixed. I used 0.0.22 and uploaded a binary. Apple reported this to me: 
Hello,
We noticed one or more issues with a recent delivery for the following app:
	•	Fluids & Particle Simulation
	•	Version 11.2.8
	•	Build 181
Please correct the following issues and upload a new binary to App Store Connect.
ITMS-90288: Invalid Code Signing Entitlements - The entitlements in your app bundle signature do not match the ones that are contained in the provisioning profile. According to the provisioning profile, the bundle contains a key value that is not allowed: 'NPA3XMW8F9.ai.fxn.fxn' for the key 'com.apple.application-identifier' in 'Fluids.app/Contents/PlugIns/Function.dylib'
ITMS-90286: Invalid Code Signing Entitlements - Your application bundle's signature contains code signing entitlements that are not supported on macOS. Specifically, value 'NPA3XMW8F9.ai.fxn.fxn' for key 'com.apple.application-identifier' in 'Fluids.app/Contents/PlugIns/Function.dylib' is not supported. This value should be a string starting with your TEAMID, followed by a dot '.', followed by the bundle identifier .
